import 'package:swipezone/repositories/location_repository.dart';
import 'package:swipezone/repositories/models/categories.dart';
import 'package:swipezone/repositories/models/localization.dart';
import 'package:swipezone/repositories/models/location.dart';

class ILocationRepository implements LocationRepository {
  @override
  Future<List<Location>> getLocations() {
    return Future.value([
      Location(
        "Tour Eiffel",
        "La Tour Eiffel est un monument emblématique de Paris, construit en 1889.",
        null,
        null,
        "https://upload.wikimedia.org/wikipedia/commons/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg",
        Categories.Tower,
        null,
        Localization("Champ de Mars, 5 Avenue Anatole France, 75007 Paris", 48.8584, 2.2945),
      ),
      Location(
        "Louvre",
        "Le Louvre est le plus grand musée d'art du monde, abritant la Joconde.",
        null,
        null,
        "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Louvre_Museum_Wikimedia_Commons.jpg/2880px-Louvre_Museum_Wikimedia_Commons.jpg",
        Categories.Museum,
        null,
        Localization("Rue de Rivoli, 75001 Paris", 48.8606, 2.3376),
      ),
      Location(
        "Cathédrale Notre-Dame",
        "La cathédrale gothique Notre-Dame est située sur l'île de la Cité.",
        null,
        null,
        "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Notre-Dame_de_Paris_2013-07-24.jpg/560px-Notre-Dame_de_Paris_2013-07-24.jpg",
        Categories.Church,
        null,
        Localization("6 Parvis Notre-Dame - Pl. Jean-Paul II, 75004 Paris",
            48.8529, 2.3508),
      ),
      Location(
        "Arc de Triomphe",
        "Construit pour honorer les victoires de Napoléon, il est situé sur la place de l'Étoile.",
        null,
        null,
        "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Arc_de_Triomphe%2C_Paris_21_October_2010.jpg/1920px-Arc_de_Triomphe%2C_Paris_21_October_2010.jpg",
        Categories.HistoricalSite,
        null,
        Localization("Place Charles de Gaulle, 75008 Paris", 48.8738, 2.295),
      ),
      Location(
        "Sacré-Cœur",
        "La basilique du Sacré-Cœur est un symbole religieux de Montmartre.",
        null,
        null,
        "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Sacr%C3%A9_Coeur_Fa%C3%A7ade_1.jpg/560px-Sacr%C3%A9_Coeur_Fa%C3%A7ade_1.jpg",
        Categories.Church,
        null,
        Localization(
            "35 Rue du Chevalier de la Barre, 75018 Paris", 48.8867, 2.3431),
      ),
      Location(
        "Panthéon",
        "Le Panthéon est un mausolée pour les grandes figures françaises.",
        null,
        null,
        "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Pantheon_of_Paris_007.JPG/520px-Pantheon_of_Paris_007.JPG",
        Categories.HistoricalSite,
        null,
        Localization("Place du Panthéon, 75005 Paris", 48.8462, 2.3449),
      ),
      Location(
        "Place de la Concorde",
        "La plus grande place de Paris, connue pour son obélisque et ses fontaines.",
        null,
        null,
        "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Place_de_la_Concorde_from_the_Eiffel_Tower%2C_Paris_April_2011.jpg/560px-Place_de_la_Concorde_from_the_Eiffel_Tower%2C_Paris_April_2011.jpg",
        Categories.HistoricalSite,
        null,
        Localization("Place de la Concorde, 75008 Paris", 48.8656, 2.3212),
      ),
      Location(
        "Palais Garnier",
        "L'Opéra Garnier est une somptueuse salle de spectacle datant du XIXe siècle.",
        null,
        null,
        "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Paris_Palais_Garnier_2010-04-06_16.55.07.jpg/660px-Paris_Palais_Garnier_2010-04-06_16.55.07.jpg",
        Categories.Museum,
        null,
        Localization("Place de l'Opéra, 75009 Paris", 48.8719, 2.3316),
      ),
      Location(
        "Jardin des Tuileries",
        "Le jardin des Tuileries est un jardin public historique situé près du Louvre.",
        null,
        null,
        "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Jardin_des_Tuileries_-_panoramio_-_Javier_B.jpg/560px-Jardin_des_Tuileries_-_panoramio_-_Javier_B.jpg",
        Categories.Park,
        null,
        Localization("113 Rue de Rivoli, 75001 Paris", 48.8636, 2.3276),
      ),
      Location(
        "Pont Alexandre III",
        "Ce pont richement orné relie les Champs-Élysées et les Invalides.",
        null,
        null,
        "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Pont_Alexandre_III_from_pont_de_la_Concorde%2C_Paris_17_May_2012.jpg/560px-Pont_Alexandre_III_from_pont_de_la_Concorde%2C_Paris_17_May_2012.jpg",
        Categories.HistoricalSite,
        null,
        Localization("Pont Alexandre III, 75008 Paris", 48.8654, 2.3131),
      ),
      Location(
        "Musée d'Orsay",
        "Un célèbre musée installé dans une ancienne gare, connu pour ses impressionnistes.",
        null,
        null,
        "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Gare_d%27Orsay_%2849570190081%29.jpg/560px-Gare_d%27Orsay_%2849570190081%29.jpg",
        Categories.Museum,
        null,
        Localization("1 Rue de la Légion d'Honneur, 75007 Paris", 48.8599, 2.3266),
        ),
      Location(
        "La Sainte-Chapelle",
        "Une chapelle gothique réputée pour ses magnifiques vitraux.",
        null,
        null,
        "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Sainte-Chapelle_de_Paris_vue_du_Palais_de_justice.JPG/460px-Sainte-Chapelle_de_Paris_vue_du_Palais_de_justice.JPG",
        Categories.Church,
        null,
        Localization("8 Boulevard du Palais, 75001 Paris", 48.8554, 2.3451),
        ),
      Location(
        "Le Marais",
        "Un quartier historique et animé, connu pour ses boutiques et galeries d'art.",
        null,
        null,
        "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Jardin_de_l%27H%C3%B4tel_Sal%C3%A9_-_L%C3%A9onor_Fini%2C_Paris_17_December_2016.jpg/560px-Jardin_de_l%27H%C3%B4tel_Sal%C3%A9_-_L%C3%A9onor_Fini%2C_Paris_17_December_2016.jpg",
        Categories.HistoricalSite,
        null,
        Localization("Le Marais, 75003 Paris", 48.8589, 2.3622),
        ),
      Location(
        "La Défense",
        "Le quartier des affaires avec des gratte-ciel modernes et la Grande Arche.",
        null,
        null,
        "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/La_D%C3%A9fense_depuis_l%27Arc_de_Triomphe_Janvier_2023_%28cropped%29.jpg/560px-La_D%C3%A9fense_depuis_l%27Arc_de_Triomphe_Janvier_2023_%28cropped%29.jpg",
        Categories.HistoricalSite,
        null,
        Localization("La Défense, 92400 Courbevoie", 48.8924, 2.2385),

      ),
    ]);
  }
}
